# fdsfsf

name: My First Action

on:
  workflow_dispatch:
  

jobs:

  build:
    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Echo
      run: echo helllo world

    - name: Setup .NET 10 SDK
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x

    - name: Echo
      run: ls -al

   
