# Some comment

name: NetX Build + Publish

on:
  workflow_dispatch:
  

jobs:

  build:
    name: Build + Publish netx
    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Starting
      run: echo [Starting Test]

    - name: Setup .NET 10 SDK
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'

    - name: See what version of .NET was installed
      run: dotnet --version
      
    - name: Restore dependencies
      run: dotnet restore
        
    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test netx
      run: dotnet run build_script.cs yabadabadoo
      
    - name: Publish to NuGet
      run: dotnet nuget push thinkmine.netx.framework.1.0.5-preview.nupkg \
            --api-key oy2cepu5cptzufschscqnsjyqgtzc4sebnnafo6fk7urrq \
            --source https://api.nuget.org/v3/index.json \
            --skip-duplicate


      
    - name: List Directories
      run: dir

    - name: Ending
      run: echo [Ending Test]
