# Second

name: workflow1

on:
  workflow_dispatch:

jobs: 
  build:
    runs-on: self-hosted
    
    steps:
      - name: task 1
        run: echo hello ${{ secrets.S1 }}
      - name: task 2
        run: echo world %AAAA%
      
   
    

  
