name: workflow2

on:
  workflow_run:
    workflows: [ "workflow1" ]   
    types:
      - completed            
jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: initial
      - run: echo world
